### ISSUE TITLE
Ending on a specifc date skips generation for that date

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-eddbk-session-generator#10]
## Symptoms

When creating a repeating rule that ends on a specific date, generation for that date does not happen.

## Steps to Reproduce

- Create a rule, using a simple session length, like `1 hour`.
- Make the rule repeat daily between two times, ex. `8:00 - 16:00`.
- Set the rule to stop repeating on a particular date, ex. `30th June`
- Generate sessions
- Observe generated sessions - 30th June should have no sessions

## Possible Cause

The date on which to stop repeating is being saved as a timestamp, converted from a date ISO8601 string, without any time (i.e. `00:00:00`). This results in the repetition stopping at the _start_ of the date, rather than at the end.

## Recommended Solution

When calculating the timestamp at which repetition should stop, a day should be added to the repetition end date, such that if the repetition end date is saved as `Y-M-D 00:00:00`, the used repetition ending timestamp is equivalent to `Y-M-[D+1] 00:00:00`.

**Comment by markzahra** [comment]
I can reproduce in Beta4 as seen in the below screenshots.

Availability: https://prnt.sc/k6rc2w
Wizard: https://prnt.sc/k6rc64

**Comment by mecha** [comment]
@markzahra I'm testing on both Beta5 and my local nightly and I cannot reproduce. Checking the changelog and `composer.lock` file shows that the solution for this bug was merged into Beta4, so you should not be experiencing this problem.

I suspect that you had already reproduced this on Beta3 and therefore already had sessions generated for it when you tried Beta4. Can you kindly trying reproducing again, after regenerating sessions on Beta4 or Beta5?

**Comment by markzahra** [comment]
@mecha I can no longer reproduce in Beta5 either.

**Comment by mecha** [comment]
Fantastic. Closing the issue.
