### ISSUE TITLE
Fix weekly repeating rule algorithm

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-eddbk-session-generator#7]
The rule should be changed to just repeat the rule's period every week.
The factory will create multiple instances of the rule, for each day of the week selected.

**Comment by markzahra** [comment]
@mecha remind me how to test this change please.

Weekly repetitions are working fine, but was there a specific case which did not work?

**Comment by mecha** [comment]
The symptoms of the previous implementation were:

- It skips the last week repetition
- If a rule starts the middle of the week, like a Wed, the previous days (Mon and Tues) have an incorrect number of repetitions.
- Sometimes an extra day's worth of sessions are generated outside of the repetition range.

If you cannot observe any of the above, kindly close the issue.

**Comment by mecha** [comment]
This issue was opened on 9th June, and the relevant code has since changed (#13). Closing.
